name: kahoot_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  qr_code_scanner: ^1.0.1
  flutter_animate: ^4.5.2
  percent_indicator: ^4.2.4
  http: ^1.3.0
  dio: ^5.8.0+1
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/font/

  fonts:
    - family: GilroyBold
      fonts:
        - asset: assets/font/Gilroy-Bold.ttf
    - family: GilroySemiBold
      fonts:
        - asset: assets/font/Gilroy-SemiBold.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/font/Gilroy-Medium.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/font/Gilroy-Regular.ttf
  # uses-material-design: true
  generate: true
