name: kahoot_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/font/

  fonts:
    - family: GilroyBold
      fonts:
        - asset: assets/font/Gilroy-Bold.ttf
    - family: GilroySemiBold
      fonts:
        - asset: assets/font/Gilroy-SemiBold.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/font/Gilroy-Medium.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/font/Gilroy-Regular.ttf
  # uses-material-design: true
  generate: true
